In [16]:
import spacy
from spacy.matcher import Matcher
from spacy.tokens import Span
from spacy import displacy
nlp = spacy.load('en_core_web_sm')
from spacy.lang.en.stop_words import STOP_WORDS

In [74]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import string

In [21]:
text = 'Apple, This is first sentence. and Google this is another one. Here 3rd one is'

In [22]:
doc = nlp(text)

In [23]:
for token in doc:
  print(token)

Apple
,
This
is
first
sentence
.
and
Google
this
is
another
one
.
Here
3rd
one
is


## **break into sentences**

In [24]:
sent = nlp.create_pipe('sentencizer')
nlp.add_pipe(sent, before='parser')

In [25]:
doc = nlp(text)

In [26]:
for sent in doc.sents:
  print(sent)

Apple, This is first sentence.
and Google this is another one.
Here 3rd one is


## **Stop words**

In [27]:
stopwords = list(STOP_WORDS)

In [28]:
stopwords

['her',
 'always',
 'it',
 'although',
 'amongst',
 'twelve',
 '’ve',
 'because',
 'another',
 'whereas',
 'herself',
 'yet',
 'be',
 'almost',
 'even',
 'however',
 'herein',
 'not',
 'once',
 'between',
 'please',
 'often',
 'how',
 'which',
 'thru',
 'due',
 'less',
 'whither',
 'into',
 'few',
 'last',
 'what',
 'used',
 'moreover',
 'least',
 'empty',
 'enough',
 'just',
 'around',
 'behind',
 'now',
 'after',
 'onto',
 'both',
 'take',
 'his',
 'whole',
 'top',
 'per',
 'hereby',
 'someone',
 'only',
 'anything',
 'anyhow',
 'move',
 'yourselves',
 'whereafter',
 'have',
 'themselves',
 'us',
 'who',
 'ca',
 'ours',
 '’re',
 'this',
 'all',
 'well',
 'since',
 'whose',
 'everywhere',
 'during',
 'our',
 "'ll",
 'do',
 'next',
 'doing',
 'hence',
 'as',
 'cannot',
 'go',
 'been',
 'some',
 'other',
 'nor',
 'much',
 'though',
 'beside',
 'therefore',
 'beforehand',
 'being',
 'rather',
 'keep',
 '‘m',
 'wherein',
 'hereafter',
 'afterwards',
 'done',
 "'m",
 'various',
 'against',

In [29]:
len(stopwords)

326

In [30]:
for token in doc:
  if token.is_stop == False:
    print(token)

Apple
,
sentence
.
Google
.
3rd


## **Lemmatization**

In [31]:
doc = nlp('run runs running runner')

In [34]:
for lem in doc:
  print(lem.text, lem.lemma_)

run run
runs run
running run
runner runner


## **Part of speech**

In [38]:
doc = nlp('All is well at your end!')

In [39]:
for token in doc:
  print(token.text, token.pos_)

All DET
is AUX
well ADV
at ADP
your DET
end NOUN
! PUNCT


In [42]:
displacy.render(doc, style='dep',jupyter=True)

## **Entity Recoginition**

In [44]:
doc = nlp("New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid an outbreak, becoming the latest national flash point over refusals to inoculate against dangerous diseases. At least 285 people have contracted measles in the city since September, mostly in Brooklyn’s Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday. The mandate orders all unvaccinated people in the area, including a concentration of Orthodox Jews, to receive inoculations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000.")

GPE means Countries, cities, states.
DATE means Absolute or relative dates or periods.
CARDINAL means Numerals that do not fall under another type.
PERSON means People, including fictional.
NORP means Nationalities or religious or political groups.
MONEY means Monetary values, including unit.

In [45]:
doc

New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid an outbreak, becoming the latest national flash point over refusals to inoculate against dangerous diseases. At least 285 people have contracted measles in the city since September, mostly in Brooklyn’s Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday. The mandate orders all unvaccinated people in the area, including a concentration of Orthodox Jews, to receive inoculations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000.

In [46]:
displacy.render(doc, style='ent',jupyter=True)

## **Text Classification**

TfidfVectorizer is used to convert the data from text to numbers.

In [48]:
!git clone https://github.com/laxmimerit/NLP-Tutorial-8---Sentiment-Classification-using-SpaCy-for-IMDB-and-Amazon-Review-Dataset.git

Cloning into 'NLP-Tutorial-8---Sentiment-Classification-using-SpaCy-for-IMDB-and-Amazon-Review-Dataset'...
remote: Enumerating objects: 16, done.
remote: Total 16 (delta 0), reused 0 (delta 0), pack-reused 16
Unpacking objects: 100% (16/16), done.


In [52]:
data_yelp = pd.read_csv('/content/NLP-Tutorial-8---Sentiment-Classification-using-SpaCy-for-IMDB-and-Amazon-Review-Dataset/datasets/yelp_labelled.txt',sep='\t', header = None)

In [53]:
data_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [54]:
columns_name = ['Review', 'Sentiment']
data_yelp.columns = columns_name

In [55]:
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [56]:
data_yelp.shape

(1000, 2)

In [59]:
data_amazon = pd.read_csv('/content/NLP-Tutorial-8---Sentiment-Classification-using-SpaCy-for-IMDB-and-Amazon-Review-Dataset/datasets/amazon_cells_labelled.txt', sep ='\t', header=None)

In [60]:
data_amazon.head()

0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [61]:
data_amazon.columns = columns_name

In [62]:
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [63]:
data_amazon.shape

(1000, 2)

In [64]:
data_imdb = pd.read_csv('/content/NLP-Tutorial-8---Sentiment-Classification-using-SpaCy-for-IMDB-and-Amazon-Review-Dataset/datasets/imdb_labelled.txt', sep='\t', header=None)

In [65]:
data_imdb.head()

0  1
0  A very, very, very slow-moving, aimless movie ...  0
1  Not sure who was more lost - the flat characte...  0
2  Attempting artiness with black & white and cle...  0
3       Very little music or anything to speak of.    0
4  The best scene in the movie was when Gerardo i...  1

In [66]:
data_imdb.columns = columns_name

In [67]:
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [68]:
data_imdb.shape

(748, 2)

In [69]:
data = data_yelp.append([data_amazon, data_imdb], ignore_index=True)

In [70]:
data.shape

(2748, 2)

In [71]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [72]:
data['Sentiment'].value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [73]:
data.isnull().sum()

Review       0
Sentiment    0
dtype: int64

## **Tokenization**

In [75]:
punct = string.punctuation

In [76]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [78]:
def text_data_cleaning(sentence):
  doc = nlp(sentence)
  tokens = []
  for token in doc:
    if token.lemma_ != '-PRON-':
      temp = token.lemma_.lower().strip()
    else:
      temp = token.lower_
    tokens.append(temp)
  cleaned_tokens = []
  for token in tokens:
    if token not in stopwords and token not in punct:
      cleaned_tokens.append(token)
  return cleaned_tokens

In [80]:
text_data_cleaning('    Hello how are you. Like this message')

['hello', 'like', 'message']

## **Vectorization feature engineering (TF-IDF)**

In [81]:
tfidf = TfidfVectorizer(tokenizer= text_data_cleaning)
classifier = LinearSVC()

In [82]:
X = data['Review']
Y = data['Sentiment']

In [83]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state = 0)

In [86]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((2198,), (550,), (2198,), (550,))

In [87]:
clf = Pipeline([('tfidf', tfidf), ('clf', classifier)])

In [88]:
clf.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=<function text_data_cleaning at 0x7fb7f5028ef0>,
                                 use_idf=True, vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept

In [89]:
y_pred = clf.predict(x_test)

In [90]:
accuracy_score(y_test, y_pred)

0.7672727272727272

In [92]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.72      0.76       279
           1       0.74      0.82      0.78       271

    accuracy                           0.77       550
   macro avg       0.77      0.77      0.77       550
weighted avg       0.77      0.77      0.77       550



In [93]:
confusion_matrix(y_test, y_pred)

array([[201,  78],
       [ 50, 221]])

In [94]:
clf.predict(['Wow, this is amazing'])

array([1])

In [96]:
clf.predict(['Wow, this sucks'])

array([0])