In [1]:
#!python -m spacy download en_core_web_lg

In [10]:
!git clone https://github.com/laxmimerit/All-CSV-ML-Data-Files-Download.git

Cloning into 'All-CSV-ML-Data-Files-Download'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 38 (delta 2), reused 4 (delta 1), pack-reused 29
Unpacking objects: 100% (38/38), done.


In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [43]:
import spacy
import pickle

In [5]:
nlp = spacy.load('en_core_web_lg')

In [6]:
x = 'dog cat lion erfrff'

In [7]:
doc = nlp(x)

In [8]:
for token1 in doc:
  for token2 in doc:
    print(token1.text, token2.text, token1.similarity(token2))

dog dog 1.0
dog cat 0.80168545
dog lion 0.47424486
dog erfrff 0.0
cat dog 0.80168545
cat cat 1.0
cat lion 0.5265438
cat erfrff 0.0
lion dog 0.47424486
lion cat 0.5265438
lion lion 1.0
lion erfrff 0.0
erfrff dog 0.0
erfrff cat 0.0
erfrff lion 0.0
erfrff erfrff 1.0


/usr/lib/python3.7/runpy.py:193: UserWarning: [W008] Evaluating Token.similarity based on empty vectors.
  "__main__", mod_spec)
/usr/lib/python3.7/runpy.py:193: UserWarning: [W008] Evaluating Token.similarity based on empty vectors.
  "__main__", mod_spec)
/usr/lib/python3.7/runpy.py:193: UserWarning: [W008] Evaluating Token.similarity based on empty vectors.
  "__main__", mod_spec)
/usr/lib/python3.7/runpy.py:193: UserWarning: [W008] Evaluating Token.similarity based on empty vectors.
  "__main__", mod_spec)
/usr/lib/python3.7/runpy.py:193: UserWarning: [W008] Evaluating Token.similarity based on empty vectors.
  "__main__", mod_spec)
/usr/lib/python3.7/runpy.py:193: UserWarning: [W008] Evaluating Token.similarity based on empty vectors.
  "__main__", mod_spec)


### **Build a model**

In [11]:
data = pd.read_csv('/content/All-CSV-ML-Data-Files-Download/moviereviews.tsv',sep='\t')

In [12]:
data.head()

label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

In [13]:
!pip install git+https://github.com/laxmimerit/preprocess_kgptalkie.git

  Cloning https://github.com/laxmimerit/preprocess_kgptalkie.git to /tmp/pip-req-build-aw1c9ebt
  Running command git clone -q https://github.com/laxmimerit/preprocess_kgptalkie.git /tmp/pip-req-build-aw1c9ebt
  Created wheel for preprocess-kgptalkie: filename=preprocess_kgptalkie-0.1.3-py3-none-any.whl size=11756 sha256=7b39ada7c623782bfc48c017185c107dfbb3a230a016073f488e684712cbf217
  Stored in directory: /tmp/pip-ephem-wheel-cache-tjr53324/wheels/0d/b3/29/bfe3deffda68980088d17b81331be6667e837ffb4a071bae82
Successfully built preprocess-kgptalkie


In [14]:
def get_clean(x):
    x = str(x).lower().replace('\\', '').replace('_', ' ')
    x = ps.cont_exp(x)
    x = ps.remove_emails(x)
    x = ps.remove_urls(x)
    x = ps.remove_html_tags(x)
    x = ps.remove_rt(x)
    x = ps.remove_accented_chars(x)
    x = ps.remove_special_chars(x)
    x = re.sub("(.)\\1{2,}", "\\1", x)
    return x

In [15]:
import preprocess_kgptalkie as ps
import re

In [16]:
data['review'] = data['review'].apply(lambda x: get_clean(x))

In [17]:
data.head()

label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

### **Word2vec conversion**

In [18]:
x = 'cat dog'
doc = nlp(x)

In [19]:
doc.vector # vector for both cat and dog together

array([-2.76215017e-01,  1.73051000e-01, -1.06199495e-01, -2.87514985e-01,
       -6.71409965e-02,  3.10755014e-01, -1.97300002e-01, -2.83794999e-01,
        9.76060033e-02,  1.66744995e+00, -6.34269953e-01,  9.63025019e-02,
       -6.48334980e-01,  1.21810503e-01, -2.99584985e-01,  2.50550002e-01,
        2.70019501e-01,  1.12965000e+00, -1.50799975e-02, -3.55899990e-01,
       -3.66439998e-01, -6.04224950e-02,  5.51749915e-02, -3.11755002e-01,
        3.66990000e-01, -1.74511507e-01, -3.25464994e-01, -4.03584987e-01,
        2.28844002e-01, -1.20778494e-01, -6.23224974e-01,  6.32480010e-02,
       -1.10113002e-01,  4.38295007e-01,  3.05490017e-01,  6.75000250e-03,
        5.48135042e-01, -8.55714977e-01, -1.13398999e-01,  1.28289998e-01,
        2.71515012e-01,  1.46710008e-01, -1.70319498e-01, -3.54690015e-01,
        2.79549956e-02, -1.16696998e-01, -4.24840003e-01,  2.22696498e-01,
       -4.93499637e-03, -2.17053995e-01,  1.82810009e-01,  9.06850100e-02,
        1.11986503e-01,  

In [20]:
doc.vector.shape

(300,)

In [21]:
for token in doc:
  print(token.text)

cat
dog


In [22]:
doc[0].vector # vector only for a cat

array([-0.15067  , -0.024468 , -0.23368  , -0.23378  , -0.18382  ,
        0.32711  , -0.22084  , -0.28777  ,  0.12759  ,  1.1656   ,
       -0.64163  , -0.098455 , -0.62397  ,  0.010431 , -0.25653  ,
        0.31799  ,  0.037779 ,  1.1904   , -0.17714  , -0.2595   ,
       -0.31461  ,  0.038825 , -0.15713  , -0.13484  ,  0.36936  ,
       -0.30562  , -0.40619  , -0.38965  ,  0.3686   ,  0.013963 ,
       -0.6895   ,  0.004066 , -0.1367   ,  0.32564  ,  0.24688  ,
       -0.14011  ,  0.53889  , -0.80441  , -0.1777   , -0.12922  ,
        0.16303  ,  0.14917  , -0.068429 , -0.33922  ,  0.18495  ,
       -0.082544 , -0.46892  ,  0.39581  , -0.13742  , -0.35132  ,
        0.22223  , -0.144    , -0.048287 ,  0.3379   , -0.31916  ,
        0.20526  ,  0.098624 , -0.23877  ,  0.045338 ,  0.43941  ,
        0.030385 , -0.013821 , -0.093273 , -0.18178  ,  0.19438  ,
       -0.3782   ,  0.70144  ,  0.16236  ,  0.0059111,  0.024898 ,
       -0.13613  , -0.11425  , -0.31598  , -0.14209  ,  0.0281

In [23]:
doc[0].vector.shape # shape of the vector is always 300

(300,)

In [24]:
def get_vec(x):
  doc = nlp(x)
  vec = doc.vector
  return vec


In [25]:
get_vec(x)

array([-2.76215017e-01,  1.73051000e-01, -1.06199495e-01, -2.87514985e-01,
       -6.71409965e-02,  3.10755014e-01, -1.97300002e-01, -2.83794999e-01,
        9.76060033e-02,  1.66744995e+00, -6.34269953e-01,  9.63025019e-02,
       -6.48334980e-01,  1.21810503e-01, -2.99584985e-01,  2.50550002e-01,
        2.70019501e-01,  1.12965000e+00, -1.50799975e-02, -3.55899990e-01,
       -3.66439998e-01, -6.04224950e-02,  5.51749915e-02, -3.11755002e-01,
        3.66990000e-01, -1.74511507e-01, -3.25464994e-01, -4.03584987e-01,
        2.28844002e-01, -1.20778494e-01, -6.23224974e-01,  6.32480010e-02,
       -1.10113002e-01,  4.38295007e-01,  3.05490017e-01,  6.75000250e-03,
        5.48135042e-01, -8.55714977e-01, -1.13398999e-01,  1.28289998e-01,
        2.71515012e-01,  1.46710008e-01, -1.70319498e-01, -3.54690015e-01,
        2.79549956e-02, -1.16696998e-01, -4.24840003e-01,  2.22696498e-01,
       -4.93499637e-03, -2.17053995e-01,  1.82810009e-01,  9.06850100e-02,
        1.11986503e-01,  

In [26]:
#get vector for each of the rows in the data
data['vec'] = data['review'].apply(lambda x : get_vec(x))

In [27]:
data.head()

label  ...                                                vec
0   neg  ...  [-0.024749208, 0.05506309, -0.1091559, -0.0209...
1   neg  ...  [-0.021686133, 0.12117902, -0.13109466, -0.021...
2   pos  ...  [0.016552947, 0.11237219, -0.07840806, -0.0179...
3   pos  ...  [0.022948751, 0.074571006, -0.06255964, -0.039...
4   neg  ...  [0.016205939, 0.06909881, -0.116068244, -0.027...

[5 rows x 3 columns]

In [28]:
X = data['vec'].to_numpy()

In [29]:
X.shape

(2000,)

In [30]:
X = X.reshape(-1,1)

In [31]:
X.shape

(2000, 1)

In [32]:
X

array([[array([-2.47492082e-02,  5.50630912e-02, -1.09155901e-01, -2.09761988e-02,
        5.14255241e-02, -2.73563322e-02,  2.82345130e-03, -1.07418865e-01,
        4.56782617e-02,  2.10219669e+00, -1.08040214e-01, -1.52518107e-02,
       -1.19990604e-02, -4.14772630e-02, -6.42440543e-02, -4.23673280e-02,
       -4.12555672e-02,  8.76505315e-01, -1.16644435e-01, -4.64346111e-02,
       -1.96756646e-02, -4.43504229e-02, -4.20983210e-02, -1.23986332e-02,
        2.38176882e-02,  3.33098159e-03, -5.07248975e-02, -4.62397859e-02,
        1.09616071e-02, -6.29315600e-02, -5.12722917e-02,  7.99128786e-02,
       -9.50764269e-02,  9.63740870e-02,  7.64656439e-02, -7.78278038e-02,
       -8.62725731e-03,  4.78737652e-02, -4.18470763e-02, -1.72930937e-02,
        2.91692205e-02,  1.14286780e-01, -4.38313223e-02, -8.51681754e-02,
        9.78026465e-02,  2.06402130e-02, -6.59504458e-02,  6.28861785e-03,
       -3.39252353e-02,  2.90057249e-02,  1.51567468e-02,  5.73364757e-02,
       -2.8624856

In [33]:
# array of array, hence concatenate
X = np.concatenate(np.concatenate(X, axis=0), axis=0).reshape(-1,300)

In [34]:
X.shape

(2000, 300)

In [35]:
y = data['label']

In [37]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, stratify=y)

In [38]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((1600, 300), (400, 300), (1600,), (400,))

In [39]:
clf = LogisticRegression(solver='liblinear')

In [40]:
clf.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [41]:
y_pred = clf.predict(x_test)

In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         neg       0.75      0.80      0.77       200
         pos       0.78      0.73      0.76       200

    accuracy                           0.77       400
   macro avg       0.77      0.77      0.76       400
weighted avg       0.77      0.77      0.76       400



In [44]:
pickle.dump(clf, open('w2v_sentiment.pkl', 'wb'))

In [46]:
model = pickle.load(open('/content/w2v_sentiment.pkl', 'rb'))

In [47]:
x = 'this was really a &%good movie'
x = get_clean(x)
vec = get_vec(x)
vec

array([-8.64375010e-02,  2.03543141e-01, -8.56069997e-02, -2.35399976e-02,
        8.52973387e-02,  7.79276714e-02,  4.33751643e-02, -4.62763309e-01,
        5.36908358e-02,  2.42433333e+00, -1.84253335e-01,  9.41810012e-02,
        1.41268149e-01, -2.44086725e-03, -2.29101658e-01, -1.84795424e-01,
       -7.31567061e-03,  9.96933281e-01, -2.31155679e-01, -1.04433426e-03,
       -3.83930020e-02, -3.24846715e-01,  1.39068335e-01,  1.87539998e-02,
       -2.02641636e-02,  1.74961329e-01, -4.77533676e-02, -1.87537983e-01,
       -6.40466586e-02, -1.47629842e-01, -3.23046669e-02,  6.44022226e-03,
        5.18165082e-02, -7.04866648e-03,  4.70666820e-03, -1.06669605e-01,
        1.37790412e-01, -7.70291612e-02, -2.75780529e-01, -2.46405005e-01,
        1.54971495e-01,  2.05878317e-01,  8.84184241e-02, -1.61607996e-01,
        2.18816683e-01,  1.47549495e-01, -2.23486677e-01, -3.81355025e-02,
       -1.27872840e-01, -6.67368248e-02, -6.70833513e-02,  2.01637492e-01,
        1.27364829e-01,  

In [50]:
model.predict(vec.reshape(1,-1))

array(['pos'], dtype=object)