In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten

In [42]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score

In [8]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')

In [9]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [11]:
X = dataset.drop(labels=['RowNumber', 'CustomerId', 'Surname','Exited'],axis=1)
Y = dataset['Exited']

In [15]:
label1 = LabelEncoder()
X['Geography'] = label1.fit_transform(X['Geography'])

In [16]:
X.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [17]:
label2 = LabelEncoder()
X['Gender'] = label2.fit_transform(X['Gender'])

In [18]:
X.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [19]:
X = pd.get_dummies(X, drop_first=True, columns=['Geography'])

In [20]:
X.head()

CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0          619       0   42  ...        101348.88            0            0
1          608       0   41  ...        112542.58            0            1
2          502       0   42  ...        113931.57            0            0
3          699       0   39  ...         93826.63            0            0
4          850       0   43  ...         79084.10            0            1

[5 rows x 11 columns]

### Feature standardization

In [25]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state =0)

In [26]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [28]:
x_train

array([[ 0.16958176, -1.09168714, -0.46460796, ...,  1.10643166,
        -0.5698444 ,  1.74309049],
       [-2.30455945,  0.91601335,  0.30102557, ..., -0.74866447,
         1.75486502, -0.57369368],
       [-1.19119591, -1.09168714, -0.94312892, ...,  1.48533467,
        -0.5698444 , -0.57369368],
       ...,
       [ 0.9015152 ,  0.91601335, -0.36890377, ...,  1.41231994,
        -0.5698444 , -0.57369368],
       [-0.62420521, -1.09168714, -0.08179119, ...,  0.84432121,
        -0.5698444 ,  1.74309049],
       [-0.28401079, -1.09168714,  0.87525072, ...,  0.32472465,
         1.75486502, -0.57369368]])

In [29]:
model = Sequential()
model.add(Dense(X.shape[1],activation='relu', input_dim = X.shape[1]))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [31]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [36]:
model.fit(x_train,y_train.to_numpy(),epochs=10,batch_size=10, verbose=1)

Epoch 1/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3360 - accuracy: 0.8619
Epoch 2/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3335 - accuracy: 0.8605
Epoch 3/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3331 - accuracy: 0.8646
Epoch 4/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3316 - accuracy: 0.8649
Epoch 5/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3312 - accuracy: 0.8648
Epoch 6/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3291 - accuracy: 0.8650
Epoch 7/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3285 - accuracy: 0.8630
Epoch 8/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3263 - accuracy: 0.8644
Epoch 9/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3267 - accuracy: 0.8635
Epoch 10/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3263 - accuracy: 0.8665

In [37]:
y_pred = model.predict_classes(x_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [39]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [41]:
model.evaluate(x_test,y_test.to_numpy())

63/63 [==============================] - 0s 1ms/step - loss: 0.3430 - accuracy: 0.8580


[0.34300434589385986, 0.8579999804496765]

In [43]:
  confusion_matrix(y_test, y_pred)

array([[1498,   97],
       [ 187,  218]])

In [44]:
accuracy_score(y_test,y_pred)

0.858